### ISSUE TITLE
ParserError when there are only student comments and no submission files/texts

### ISSUE THREAD

**Issue by christofferqa** [Mortal/bbfetch#4]
Issuing `./grading -d` successfully downloads a bunch of handins, but then fails with a parseerror for one handin:

```
[2016-11-19 14:20:22,120 INFO] Fetch details for attempt (...)
[2016-11-19 14:20:23,157 ERROR] Parsing error
No currentAttempt_submissionList
ParserError logged to 2016-11-19_1420_parseerror.txt
```

As a result, the program terminates, and all of the remaining handins are not downloaded either.

**Comment by Mortal** [comment]
Hi Christoffer, I'd like to look into this. Can you please email me `2016-11-19_1420_parseerror.txt` at rav@cs.au.dk?

**Comment by Mortal** [comment]
It is unfortunate when students don't hand in anything. In this case the student at least wrote a comment (which goes into the file `student_comments.txt`), so I've changed the behavior to only raising ParserError when there is no submission AND no comments.
