### ISSUE TITLE
Limited to 3 attempts?

### ISSUE THREAD

**Issue by christofferqa** [Mortal/bbfetch#6]
Is bbfetch only showing three attempts per student for each handin? I just realized that some students apparently resubmitted handins a long time ago in Blackboard, although this does not show up in bbfetch's overview.

**Comment by Mortal** [comment]
Yes! Probably we should have a better default implementation of `Grading.get_assignment_display` (which is the function you can modify). You can also change the column width in `get_gradebook_columns` if you need to. Ultimately the place that cuts off the data is the call to `truncate_name` in `print_gradebook`. The function `truncate_name(s, n)` is simply `s[:n]` if `s` does not contain spaces (and it does something more clever when the string has spaces).
