### ISSUE TITLE
Grade Table ignores overridden grades

### ISSUE THREAD

**Issue by kbadk** [Mortal/bbfetch#7]
When manually overriding a grade in the Grade Centre in Blackboard, the initial grade given for an attempt is still shown in bbfetch's grade table.

If, for instance, I fail a student's assignment, but later change the assignment's grade to "passed", the table shown when doing `./grading -a` will still say "✘".

The calculated points at the end of the row is still correct, though.

**Comment by Mortal** [comment]
Yes, this is a bug.

The overridden grade is already retrieved in [bbfetch/backend.py fetch_overview](https://github.com/Mortal/bbfetch/blob/527684906f998fcc22302da20ffde635b6c35ff2/blackboard/backend.py#L87), so it should be possible to modify/override [Grading.get_assignment_display](https://github.com/Mortal/bbfetch/blob/527684906f998fcc22302da20ffde635b6c35ff2/blackboard/grading.py#L175) by checking [the StudentAssignment.score attribute](https://github.com/Mortal/bbfetch/blob/527684906f998fcc22302da20ffde635b6c35ff2/blackboard/gradebook.py#L268) of the assignment at hand, that is, returning a check mark in get_assignment_display if `student_assignment.score > 0`.

@kbadk Can you try adding the following method to your Grading class and report if it works?

```python
    def get_assignment_display(self, u, assignment):
        try:
            student_assignment = u.assignments[assignment.id]
        except KeyError:
            return ''
        if student_assignment.score > 0:
            return '\u2714'
        return super().get_assignment_display(u, assignment)
```

**Comment by kbadk** [comment]
That does indeed solve the problem. Thanks!
